[package]
name = "surff"
version = "0.1.0"
authors = ["Oktay KÖSE <oktaykose13@gmail.com>"]
edition = "2021"
description = "web server"
license = "MIT"

[dependencies]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3